var series = [
{ titre : "Sleepy Hollow", titreImg : "sleepyhollow", annee:2017, genre: "Horreur", video:"https://www.youtube.com/watch?v=1hFg9qS_u3w&feature=youtu.be", resumer:""},
{ titre : "Dr House", titreImg : "drhouse", annee:2005, genre: "Medical"},
{ titre : "The Americans", titreImg : "theamericans", annee:2010, genre: "Thiller"},
{ titre : "Salem", titreImg : "salem", annee:2011, genre: "Horeur"},
{ titre : "Black Miror", titreImg : "blackmiror", annee:1996, genre: "Dramatique"},
{ titre : "Mr Robot", titreImg : "mrrobot", annee:2002, genre: "Dramatique"},
{ titre : "The 100", titreImg : "the100", annee:1995, genre: "Scifi"},
{ titre : "Weeds", titreImg : "weeds", annee:2010, genre: "Thriller/Comedie"},
{ titre : "Iron Fist", titreImg : "ironfist", annee:1980, genre: "Scifi"},
{ titre : "Dr Who", titreImg : "drwho", annee:2004, genre: "Scifi"},
{ titre : "Scorpion", titreImg : "scorpions", annee:2016, genre: "Avanture"},
{ titre : "The Walking Dead", titreImg : "thewalkingdead", annee:2006, genre: "Horreur"},
{ titre : "Blacklist", titreImg : "blacklist", annee:2014, genre: "Thiller"},
{ titre : "Zombieland", titreImg : "zombieland", annee:2001, genre: "Comedie/Horreur"},
// { titre : "", titreImg : "", annee:20, genre: ""},
// { titre : "", titreImg : "", annee:20, genre: ""},
// { titre : "", titreImg : "", annee:20, genre: ""},
// { titre : "", titreImg : "", annee:20, genre: ""},
// { titre : "", titreImg : "", annee:20, genre: ""},
// { titre : "", titreImg : "", annee:20, genre: ""},
// { titre : "", titreImg : "", annee:20, genre: ""},
// { titre : "", titreImg : "", annee:20, genre: ""},
// { titre : "", titreImg : "", annee:20, genre: ""},
// { titre : "", titreImg : "", annee:20, genre: ""},
];
